/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RunHistoryRouteImport } from './routes/run-history'
import { Route as RankedCandidatesRouteImport } from './routes/ranked-candidates'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LedgersRouteImport } from './routes/ledgers'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as AttemptsRouteImport } from './routes/attempts'
import { Route as IndexRouteImport } from './routes/index'

const RunHistoryRoute = RunHistoryRouteImport.update({
  id: '/run-history',
  path: '/run-history',
  getParentRoute: () => rootRouteImport,
} as any)
const RankedCandidatesRoute = RankedCandidatesRouteImport.update({
  id: '/ranked-candidates',
  path: '/ranked-candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgersRoute = LedgersRouteImport.update({
  id: '/ledgers',
  path: '/ledgers',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const AttemptsRoute = AttemptsRouteImport.update({
  id: '/attempts',
  path: '/attempts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attempts': typeof AttemptsRoute
  '/earnings': typeof EarningsRoute
  '/ledgers': typeof LedgersRoute
  '/portfolio': typeof PortfolioRoute
  '/ranked-candidates': typeof RankedCandidatesRoute
  '/run-history': typeof RunHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attempts': typeof AttemptsRoute
  '/earnings': typeof EarningsRoute
  '/ledgers': typeof LedgersRoute
  '/portfolio': typeof PortfolioRoute
  '/ranked-candidates': typeof RankedCandidatesRoute
  '/run-history': typeof RunHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attempts': typeof AttemptsRoute
  '/earnings': typeof EarningsRoute
  '/ledgers': typeof LedgersRoute
  '/portfolio': typeof PortfolioRoute
  '/ranked-candidates': typeof RankedCandidatesRoute
  '/run-history': typeof RunHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attempts'
    | '/earnings'
    | '/ledgers'
    | '/portfolio'
    | '/ranked-candidates'
    | '/run-history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attempts'
    | '/earnings'
    | '/ledgers'
    | '/portfolio'
    | '/ranked-candidates'
    | '/run-history'
  id:
    | '__root__'
    | '/'
    | '/attempts'
    | '/earnings'
    | '/ledgers'
    | '/portfolio'
    | '/ranked-candidates'
    | '/run-history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttemptsRoute: typeof AttemptsRoute
  EarningsRoute: typeof EarningsRoute
  LedgersRoute: typeof LedgersRoute
  PortfolioRoute: typeof PortfolioRoute
  RankedCandidatesRoute: typeof RankedCandidatesRoute
  RunHistoryRoute: typeof RunHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/run-history': {
      id: '/run-history'
      path: '/run-history'
      fullPath: '/run-history'
      preLoaderRoute: typeof RunHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranked-candidates': {
      id: '/ranked-candidates'
      path: '/ranked-candidates'
      fullPath: '/ranked-candidates'
      preLoaderRoute: typeof RankedCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledgers': {
      id: '/ledgers'
      path: '/ledgers'
      fullPath: '/ledgers'
      preLoaderRoute: typeof LedgersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attempts': {
      id: '/attempts'
      path: '/attempts'
      fullPath: '/attempts'
      preLoaderRoute: typeof AttemptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttemptsRoute: AttemptsRoute,
  EarningsRoute: EarningsRoute,
  LedgersRoute: LedgersRoute,
  PortfolioRoute: PortfolioRoute,
  RankedCandidatesRoute: RankedCandidatesRoute,
  RunHistoryRoute: RunHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
