import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  collectMinerEnvVars,
  isMinerEnvVar,
  renderMinerEnvReferenceMarkdown,
  writeMinerEnvReference,
} from "../../packages/gittensory-miner/scripts/generate-env-reference.mjs";

function fixtureRoot(): string {
  const root = mkdtempSync(join(tmpdir(), "gt-miner-env-reference-"));
  mkdirSync(join(root, "packages", "gittensory-miner", "lib"), { recursive: true });
  writeFileSync(
    join(root, "packages", "gittensory-miner", "lib", "a.js"),
    [
      "export function readEnv(env = process.env) {",
      "  const ignored = process.env.OTHER_APP_VAR;",
      "  const config = env.GITTENSORY_MINER_CONFIG_DIR ?? '';",
      "  const provider = env.MINER_CODING_AGENT_PROVIDER ?? '';",
      "  return resolveLocalStoreDbPath('state.sqlite3', 'GITTENSORY_MINER_RUN_STATE_DB', env);",
      "}",
      "",
    ].join("\n"),
  );
  writeFileSync(
    join(root, "packages", "gittensory-miner", "lib", "b.js"),
    [
      "export function duplicate(env = process.env) {",
      "  return env.GITTENSORY_MINER_CONFIG_DIR;",
      "}",
      "",
    ].join("\n"),
  );
  return root;
}

describe("generate-env-reference (#5179)", () => {
  it("filters to GITTENSORY_MINER_* and MINER_* vars only", () => {
    expect(isMinerEnvVar("GITTENSORY_MINER_CONFIG_DIR")).toBe(true);
    expect(isMinerEnvVar("MINER_CODING_AGENT_PROVIDER")).toBe(true);
    expect(isMinerEnvVar("OTHER_APP_VAR")).toBe(false);
  });

  it("extracts static env reads, resolveLocalStoreDbPath names, and first references", () => {
    expect(collectMinerEnvVars({ rootDir: fixtureRoot() })).toEqual([
      {
        name: "GITTENSORY_MINER_CONFIG_DIR",
        firstReference: "lib/a.js",
        defaultValue: "",
      },
      {
        name: "GITTENSORY_MINER_RUN_STATE_DB",
        firstReference: "lib/a.js",
        defaultValue: null,
      },
      {
        name: "MINER_CODING_AGENT_PROVIDER",
        firstReference: "lib/a.js",
        defaultValue: "",
      },
    ]);
  });

  it("renders a deterministic markdown table with names, references, and defaults", () => {
    expect(
      renderMinerEnvReferenceMarkdown([
        { name: "GITTENSORY_MINER_CONFIG_DIR", firstReference: "lib/a.js", defaultValue: "" },
        { name: "GITTENSORY_MINER_RUN_STATE_DB", firstReference: "lib/run-state.js", defaultValue: null },
      ]),
    ).toBe(
      [
        "# gittensory-miner environment variable reference",
        "",
        "Generated by `npm run miner:env-reference`. Do not edit manually.",
        "",
        "| Name | First reference | Default |",
        "| --- | --- | --- |",
        "| `GITTENSORY_MINER_CONFIG_DIR` | `lib/a.js` | `\"\"` |",
        "| `GITTENSORY_MINER_RUN_STATE_DB` | `lib/run-state.js` | (none) |",
        "",
      ].join("\n"),
    );
  });

  it("writes the generated doc and reports stale output in check mode", () => {
    const root = fixtureRoot();
    const outputPath = "packages/gittensory-miner/docs/env-reference.md";
    const outputAbs = join(root, outputPath);

    const written = writeMinerEnvReference({ rootDir: root, outputPath });
    expect(written.changed).toBe(true);
    expect(existsSync(outputAbs)).toBe(true);
    const generated = readFileSync(outputAbs, "utf8");
    expect(generated).toContain("GITTENSORY_MINER_CONFIG_DIR");

    expect(writeMinerEnvReference({ rootDir: root, outputPath, check: true }).changed).toBe(false);

    writeFileSync(outputAbs, "stale\n");
    const stale = writeMinerEnvReference({ rootDir: root, outputPath, check: true });
    expect(stale.changed).toBe(true);
    expect(readFileSync(outputAbs, "utf8")).toBe("stale\n");

    const rewritten = writeMinerEnvReference({ rootDir: root, outputPath });
    expect(rewritten.changed).toBe(true);
    expect(readFileSync(outputAbs, "utf8")).toBe(generated);
  });

  it("REGRESSION: output is byte-for-byte deterministic across two runs on an unchanged tree", () => {
    const root = fixtureRoot();
    const outputPath = "packages/gittensory-miner/docs/env-reference.md";
    writeMinerEnvReference({ rootDir: root, outputPath });
    const first = readFileSync(join(root, outputPath), "utf8");
    writeMinerEnvReference({ rootDir: root, outputPath });
    const second = readFileSync(join(root, outputPath), "utf8");
    expect(second).toBe(first);
  });
});
