import { describe, expect, it } from "vitest";

import { formStateToYaml, type GeneratorFormState } from "@/lib/config-generator-yaml";

const HEADER = "# .loopover.yml — generated by the config generator";

describe("formStateToYaml", () => {
  it("serializes a full gate.aiReview config with every field set", () => {
    const state: GeneratorFormState = {
      gate: {
        aiReview: {
          combine: "consensus",
          provider: "anthropic",
          model: "claude-3-5-sonnet-latest",
        },
      },
    };
    expect(formStateToYaml(state)).toBe(
      [
        HEADER,
        "gate:",
        "  aiReview:",
        "    combine: consensus",
        "    provider: anthropic",
        "    model: claude-3-5-sonnet-latest",
      ].join("\n"),
    );
  });

  it("omits unset keys for a partial config (only provider set)", () => {
    const state: GeneratorFormState = { gate: { aiReview: { provider: "openai" } } };
    expect(formStateToYaml(state)).toBe(
      [HEADER, "gate:", "  aiReview:", "    provider: openai"].join("\n"),
    );
  });

  it("omits unset keys for a partial config (only combine and model set)", () => {
    const state: GeneratorFormState = { gate: { aiReview: { combine: "single", model: "gpt-5" } } };
    expect(formStateToYaml(state)).toBe(
      [HEADER, "gate:", "  aiReview:", "    combine: single", "    model: gpt-5"].join("\n"),
    );
  });

  it("emits only the header for a fully empty state", () => {
    expect(formStateToYaml({})).toBe(HEADER);
  });

  it("emits only the header when gate is present but aiReview is unset", () => {
    expect(formStateToYaml({ gate: {} })).toBe(HEADER);
  });

  it("treats null fields the same as unset (omitted, not emitted as `null`)", () => {
    const state: GeneratorFormState = {
      gate: { aiReview: { combine: null, provider: null, model: null } },
    };
    expect(formStateToYaml(state)).toBe(HEADER);
  });

  it("treats an empty-string model as unset rather than emitting a blank value", () => {
    const state: GeneratorFormState = { gate: { aiReview: { provider: "anthropic", model: "" } } };
    expect(formStateToYaml(state)).toBe(
      [HEADER, "gate:", "  aiReview:", "    provider: anthropic"].join("\n"),
    );
  });

  it("quotes a model value containing YAML-special characters", () => {
    const state: GeneratorFormState = { gate: { aiReview: { model: "claude: sonnet" } } };
    expect(formStateToYaml(state)).toBe(
      [HEADER, "gate:", "  aiReview:", `    model: ${JSON.stringify("claude: sonnet")}`].join("\n"),
    );
  });

  it("quotes a model value with leading/trailing whitespace", () => {
    const state: GeneratorFormState = { gate: { aiReview: { model: " claude " } } };
    expect(formStateToYaml(state)).toBe(
      [HEADER, "gate:", "  aiReview:", `    model: ${JSON.stringify(" claude ")}`].join("\n"),
    );
  });
});
